# Version of Docker-compose
version: '2'
services:
  # Add the node-js service
  node:
  # Location to the node.js dockerfile
    build: 
      context: ./server
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: node-container
    ports:
       # Host port:Container port
      - '5000:5000'
    volumes:
      # Bind-mounts configuration
      - ./server:/app
      # Ignoring any changes made in the "node_modules" folder
      - /app/node_modules
  react:
  # Location to the react.js dockerfile
    build: 
      context: ./a3
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: react-container
    ports:
     # Host port:Container port
      - '3000:3000'
    stdin_open: true